# -*- coding: utf-8 -*-
"""
CBDB 视图列名 → 中文标签。

为什么单独一个文件：
  view_meta.json 是「剖析数据库」的产物，跑一次要几十秒；
  而标签是人写的、会反复改。两者分开，改标签只需 `--labels-only` 就地打补丁。

标签分两层：
  1. COLUMN_LABELS   同一列名在多数视图里含义相同时的默认中文名
  2. VIEW_OVERRIDES  少数列在不同视图里含义不同（如 c_title_chn 在别处是「出处文献名」，
                     在 View_BiogTextData 里是「著作名」），按视图覆盖

命名约定（保证同一列在任意视图里都读得懂）：
  c_xxx_chn  → 中文原名        c_xxx / c_xxx_py → 拼音/罗马字
  *_code     → 代码（数值）    *_desc / *_desc_chn → 该代码的说明文字
  c_fy_*     → 起始(first year)   c_ly_* → 终止(last year)
  c_by_*     → 生年(birth year)   c_dy_* → 卒年(death year)
  c_bi_by_*  → 机构任职起始       c_bi_ey_* → 机构任职终止
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# 一、全局默认标签
# ---------------------------------------------------------------------------
COLUMN_LABELS = {
    # ---- 人物标识与姓名 ----
    "c_personid": "人物ID",
    "c_name": "姓名（拼音）",
    "c_name_chn": "姓名",
    "c_name_proper": "姓名（威妥玛）",
    "c_name_rm": "姓名（罗马字）",
    "c_surname": "姓（拼音）",
    "c_surname_chn": "姓",
    "c_surname_proper": "姓（威妥玛）",
    "c_surname_rm": "姓（罗马字）",
    "c_mingzi": "名（拼音）",
    "c_mingzi_chn": "名",
    "c_mingzi_proper": "名（威妥玛）",
    "c_mingzi_rm": "名（罗马字）",
    "c_alt_name": "别名（拼音）",
    "c_alt_name_chn": "别名字号",
    "c_alt_name_type_code": "别名类型代码",
    "c_name_type_desc": "别名类型代码",
    "c_name_type_desc_chn": "别名类型",
    "c_female": "是否女性",
    "c_index_year": "指数年",
    "c_index_year_type_code": "指数年类型代码",
    "c_index_year_type_desc": "指数年类型",
    "c_index_year_type_hz": "指数年类型（中文）",
    "c_index_year_source_id": "指数年依据文献ID",
    "c_ethnicity_code": "族属代码",
    "c_ethnicity_desc": "族属",
    "c_ethnicity_desc_chn": "族属",
    "c_household_status_code": "户籍身份代码",
    "c_household_status_desc": "户籍身份",
    "c_household_status_desc_chn": "户籍身份",
    "c_tribe": "部落 / 民族",
    "c_choronym_code": "郡望代码",
    "c_choronym_desc": "郡望",
    "c_choronym_desc_chn": "郡望",
    "c_dy": "朝代代码",
    "c_dynasty": "朝代（拼音）",
    "c_dynasty_chn": "朝代",
    "dynasty_chn": "朝代",

    # ---- 生年（c_by_*）----
    "c_birthyear": "生年",
    "c_by_nh_code": "生年年号ID",
    "c_by_nh_chn": "生年年号",
    "c_by_nh_py": "生年年号（拼音）",
    "c_by_nh_year": "生年号纪年",
    "c_by_intercalary": "生年闰月",
    "c_by_month": "生月",
    "c_by_day": "生日",
    "c_by_day_gz": "生日干支",
    "c_by_day_gz_chn": "生日干支",
    "c_by_day_gz_py": "生日干支（拼音）",
    "c_by_range": "生年区间",
    "c_by_range_desc": "生年区间说明",
    "c_by_range_chn": "生年区间（中文）",

    # ---- 卒年（c_dy_*）----
    "c_deathyear": "卒年",
    "c_dy_nh_code": "卒年年号ID",
    "c_dy_nh_chn": "卒年年号",
    "c_dy_nh_py": "卒年年号（拼音）",
    "c_dy_nh_year": "卒年号纪年",
    "c_dy_intercalary": "卒年闰月",
    "c_dy_month": "卒月",
    "c_dy_day": "卒日",
    "c_dy_day_gz": "卒日干支",
    "c_dy_day_gz_chn": "卒日干支",
    "c_dy_day_gz_py": "卒日干支（拼音）",
    "c_dy_range": "卒年区间",
    "c_dy_range_desc": "卒年区间说明",
    "c_dy_range_chn": "卒年区间（中文）",
    "c_death_age": "享年",
    "c_death_age_range": "享年区间",
    "c_death_age_range_desc": "享年区间说明",
    "c_death_age_range_chn": "享年区间（中文）",

    # ---- 生卒范围（c_fl_*，fl = 生卒浮动范围）----
    "c_fl_earliest_year": "生年范围首（最早）",
    "c_fl_latest_year": "生年范围末（最晚）",
    "c_fl_ey_nh_code": "生年范围首年号ID",
    "c_fl_ey_nh_chn": "生年范围首年号",
    "c_fl_ey_nh_py": "生年范围首年号（拼音）",
    "c_fl_ey_nh_year": "生年范围首纪年",
    "c_fl_ey_range": "生年范围首区间",
    "c_fl_ly_nh_code": "生年范围末年号ID",
    "c_fl_ly_nh_chn": "生年范围末年号",
    "c_fl_ly_nh_py": "生年范围末年号（拼音）",
    "c_fl_ly_nh_year": "生年范围末纪年",
    "c_fl_ly_range": "生年范围末区间",

    # ---- 通用起止年（c_fy_* = 起始 / c_ly_* = 终止）----
    "c_firstyear": "起始年",
    "c_lastyear": "终止年",
    "c_fy_nh_code": "起始年号ID",
    "c_fy_nh_chn": "起始年号",
    "c_fy_nh_py": "起始年号（拼音）",
    "c_fy_nh_year": "起始纪年",
    "c_fy_intercalary": "起始年闰月",
    "c_fy_month": "起始月",
    "c_fy_day": "起始日",
    "c_fy_day_gz": "起始日干支",
    "c_fy_day_gz_chn": "起始日干支",
    "c_fy_day_gz_py": "起始日干支（拼音）",
    "c_fy_range": "起始年区间",
    "c_fy_range_desc": "起始年区间说明",
    "c_fy_range_chn": "起始年区间（中文）",
    "c_ly_nh_code": "终止年号ID",
    "c_ly_nh_chn": "终止年号",
    "c_ly_nh_py": "终止年号（拼音）",
    "c_ly_nh_year": "终止纪年",
    "c_ly_intercalary": "终止年闰月",
    "c_ly_month": "终止月",
    "c_ly_day": "终止日",
    "c_ly_day_gz": "终止日干支",
    "c_ly_day_gz_chn": "终止日干支",
    "c_ly_day_gz_py": "终止日干支（拼音）",
    "c_ly_range": "终止年区间",
    "c_ly_range_desc": "终止年区间说明",
    "c_ly_range_chn": "终止年区间（中文）",

    # ---- 通用年月日与年号 ----
    "c_year": "年份",
    "c_month": "月",
    "c_day": "日",
    "c_day_ganzhi": "日干支",
    "c_intercalary": "闰月",
    "c_nh_code": "年号ID",
    "c_nh_year": "年号纪年",
    "c_nianhao_chn": "年号",
    "c_nianhao_pin": "年号（拼音）",
    "c_ganzhi_chn": "干支",
    "c_ganzhi_py": "干支（拼音）",
    "c_range": "年份区间",
    "c_range_chn": "年份区间（中文）",
    "c_yr_range": "年份区间",
    "c_age": "年龄",

    # ---- 地址 ----
    "c_addr_id": "地点ID",
    "c_addr_name": "地名（拼音）",
    "c_addr_chn": "地名",
    "c_addr_desc": "地址类型代码",
    "c_addr_desc_chn": "地址类型",
    "c_index_addr_id": "索引地址ID",
    "c_index_addr_name": "索引地址（拼音）",
    "c_index_addr_chn": "索引地址",
    "c_index_addr_type_code": "索引地址类型代码",
    "c_index_addr_type_desc": "索引地址类型",
    "c_index_addr_type_chn": "索引地址类型",
    "c_index_addr_x_coord": "索引地址经度",
    "c_index_addr_y_coord": "索引地址纬度",
    "x_coord": "经度",
    "y_coord": "纬度",
    "c_natal": "是否籍贯",
    "c_entry_addr_id": "入仕地点ID",
    "c_entry_addr_name": "入仕地点（拼音）",
    "c_entry_addr_chn": "入仕地点",
    "c_entry_xcoord": "入仕地点经度",
    "c_entry_ycoord": "入仕地点纬度",
    "c_event_addr_name": "事件地点（拼音）",
    "c_event_addr_chn": "事件地点",
    "c_event_xcoord": "事件地点经度",
    "c_event_ycoord": "事件地点纬度",
    "c_office_addr_name": "任职地点（拼音）",
    "c_office_addr_chn": "任职地点",
    "c_possession_addr_name": "财产所在地（拼音）",
    "c_possession_addr_chn": "财产所在地",
    "c_inst_addr_id": "机构所在地ID",
    "c_inst_addr_type_code": "机构所在地类型代码",
    "c_inst_addr_type_desc": "机构所在地类型",
    "c_inst_addr_type_chn": "机构所在地类型",
    "c_inst_addr_pinyin": "机构所在地（拼音）",
    "c_inst_addr_chn": "机构所在地",
    "inst_xcoord": "机构经度",
    "inst_ycoord": "机构纬度",
    # 县级政区（本项目 View_CountyPeopleData）
    "county_addr_id": "县ID",
    "county_name": "县名（拼音）",
    "county_name_chn": "县名",
    "county_admin_type": "县级政区类型",
    "county_firstyear": "县存续起始年",
    "county_lastyear": "县存续终止年",
    "county_x_coord": "县经度",
    "county_y_coord": "县纬度",
    # ADDRESSES 表的行政层级链（belongs1 = 直接上级）
    "parent1_name_chn": "上级政区1（府 / 州）",
    "parent2_name_chn": "上级政区2（路）",
    "parent3_name_chn": "上级政区3（朝代）",
    "parent4_name_chn": "上级政区4",
    "parent5_name_chn": "上级政区5",
    "belongs_firstyear": "该政区归属起始年",
    "belongs_lastyear": "该政区归属终止年",
    "addr_relation_code": "地址关系代码",
    "addr_relation_chn": "地址关系",
    "relation_firstyear": "该地址关系起始年",
    "relation_lastyear": "该地址关系终止年",

    # ---- 亲属 ----
    "c_kin_id": "亲属ID",
    "c_kin_name": "亲属姓名（拼音）",
    "c_kin_name_chn": "亲属姓名",
    "c_kin_chn": "亲属姓名",
    "kin_personid": "亲属ID",
    "kin_name": "亲属姓名（拼音）",
    "kin_name_chn": "亲属姓名",
    "kin_surname_chn": "亲属姓",
    "kin_female": "亲属是否女性",
    "kin_index_year": "亲属指数年",
    "kin_birthyear": "亲属生年",
    "kin_deathyear": "亲属卒年",
    "kin_dynasty_chn": "亲属朝代",
    "kin_addr_chn": "亲属地址",
    "kin_identified": "亲属是否已识别",
    "c_kin_code": "亲属关系代码",
    "c_kinrel": "亲属关系",
    "c_kinrel_chn": "亲属关系",
    "kinrel": "亲属关系",
    "kinrel_chn": "亲属关系",
    "same_surname": "是否同姓",
    "generation_offset": "世代差",
    "lineage_type": "谱系类型",
    "c_upstep": "上溯世代（尊长）",
    "c_dwnstep": "下推世代（卑幼）",
    "c_colstep": "旁系世代",
    "c_marstep": "姻亲世代",

    # ---- 交游 / 社会关系 ----
    "c_assoc_id": "交游对象ID",
    "c_assoc_name": "交游对象（拼音）",
    "c_assoc_name_chn": "交游对象",
    "c_assoc_code": "交游关系代码",
    "c_assoc_desc": "交游关系",
    "c_assoc_desc_chn": "交游关系",
    "c_assoc_first_year": "交游起始年",
    "c_assoc_kin_id": "交游对象亲属ID",
    "c_assoc_kin_name": "交游对象亲属（拼音）",
    "c_assoc_kin_chn": "交游对象亲属",
    "c_assoc_kinrel": "交游对象亲属关系",
    "c_assoc_kinrel_chn": "交游对象亲属关系",
    "c_assoc_addr_name": "交游地点（拼音）",
    "c_assoc_addr_chn": "交游地点",
    "c_assoc_fy_nh_code": "交游起始年号ID",
    "c_assoc_fy_nh_chn": "交游起始年号",
    "c_assoc_fy_nh_py": "交游起始年号（拼音）",
    "c_assoc_fy_nh_year": "交游起始纪年",
    "c_assoc_fy_intercalary": "交游起始闰月",
    "c_assoc_fy_month": "交游起始月",
    "c_assoc_fy_day": "交游起始日",
    "c_assoc_claimer_id": "交游记载人ID",
    "C_assoc_claimer_name": "交游记载人姓名（拼音）",
    "c_assoc_claimer_chn": "交游记载人",
    "c_node_id": "关联对象ID",
    "c_node_name": "关联对象（拼音）",
    "c_node_chn": "关联对象",
    "c_link_code": "关联关系代码",
    "c_link_desc": "关联关系",
    "c_link_chn": "关联关系",
    "c_link_count": "关联记载数",
    "c_lit_genre_desc": "文献体裁代码",
    "c_lit_genre_desc_chn": "文献体裁",
    "c_occasion_desc": "场合代码",
    "c_occasion_desc_chn": "场合",
    "c_topic_desc": "主题代码",
    "c_topic_desc_chn": "主题",

    # ---- 入仕 / 任官 ----
    "c_entry_code": "入仕途径代码",
    "c_entry_desc": "入仕途径",
    "c_entry_desc_chn": "入仕途径",
    "c_entry_nh_id": "入仕年号ID",
    "c_entry_nh_year": "入仕纪年",
    "c_entry_range": "入仕年份区间",
    "c_exam_field": "考试科目",
    "c_exam_rank": "科第名次",
    "c_attempt_count": "应试次数",
    "c_parental_status_code": "亲属存殁状态代码",
    "c_parental_status_desc": "亲属存殁状态",
    "c_parental_status_desc_chn": "亲属存殁状态",
    "c_office_id": "官职ID",
    "c_office_chn": "官职名",
    "c_office_pinyin": "官职名（拼音）",
    "c_office_trans": "官职英译",
    "c_office_category_id": "官职类别ID",
    "c_category_desc": "官职类别代码",
    "c_category_desc_chn": "官职类别",
    "c_posting_id": "任命ID",
    "c_posting_notes": "任命备注",
    "c_appt_code": "任命类型代码",
    "c_appt_desc": "任命类型",
    "c_appt_desc_chn": "任命类型",
    "c_assume_office_code": "就任方式代码",
    "c_assume_office_desc": "就任方式",
    "c_assume_office_desc_chn": "就任方式",
    # 机构任职（c_bi_* = BIOG_INST）
    "c_bi_role_code": "机构任职角色代码",
    "c_bi_role_desc": "机构任职角色",
    "c_bi_role_chn": "机构任职角色",
    "c_bi_begin_year": "任职起始年",
    "c_bi_by_nh_code": "任职起始年号ID",
    "c_bi_by_nh_chn": "任职起始年号",
    "c_bi_by_nh_py": "任职起始年号（拼音）",
    "c_bi_by_nh_year": "任职起始纪年",
    "c_bi_by_range": "任职起始年区间",
    "c_bi_by_range_desc": "任职起始年区间说明",
    "c_bi_by_range_chn": "任职起始年区间（中文）",
    "c_bi_end_year": "任职终止年",
    "c_bi_ey_nh_code": "任职终止年号ID",
    "c_bi_ey_nh_chn": "任职终止年号",
    "c_bi_ey_nh_py": "任职终止年号（拼音）",
    "c_bi_ey_nh_year": "任职终止纪年",
    "c_bi_ey_range": "任职终止年区间",
    "c_bi_ey_range_desc": "任职终止年区间说明",
    "c_bi_ey_range_chn": "任职终止年区间（中文）",

    # ---- 机构 / 身份 ----
    "c_inst_code": "机构ID",
    "c_inst_name_code": "机构名称ID",
    "c_inst_name_hz": "机构名",
    "c_inst_name_py": "机构名（拼音）",
    "c_status_code": "身份代码",
    "c_status_desc": "身份",
    "c_status_desc_chn": "身份",
    "c_supplement": "补充说明",

    # ---- 文献 / 著作 ----
    "c_textid": "文献ID",
    "c_text_title": "文献标题",
    "c_title": "出处文献名（拼音）",
    "c_title_chn": "出处文献名",
    "c_source": "出处文献ID",
    "c_source_title": "出处文献名（拼音）",
    "c_source_chn": "出处文献名",
    "c_source_py": "出处文献名（拼音）",
    "c_main_source": "是否主要出处",
    "c_pages": "页码",
    "c_notes": "备注",
    "c_hyperlink": "超链接",
    "c_url_api": "CBDB 原文链接",
    "c_url_api_coda": "CBDB CoDA 链接",
    "c_url_homepage": "主页链接",
    "c_person_text_title": "人物著作",
    "c_person_text_pages": "人物著作页码",
    "c_person_text_notes": "人物著作备注",
    "c_role_id": "角色ID",
    "c_role_desc": "角色",
    "c_role_desc_chn": "角色",
    "c_sequence": "序号",

    # ---- 事件 ----
    "c_event_code": "事件代码",
    "c_event_name": "事件名（拼音）",
    "c_event_name_chn": "事件名",
    "c_event_day_gz_chn": "事件日干支",
    "c_event_day_gz_py": "事件日干支（拼音）",
    "c_role": "事件角色",

    # ---- 财产 ----
    "c_possession_record_id": "财产记录ID",
    "c_possession_act_code": "财产处置方式代码",
    "c_possession_act_desc": "财产处置方式",
    "c_possession_act_desc_chn": "财产处置方式",
    "c_possession_desc": "财产描述",
    "c_possession_desc_chn": "财产描述",
    "c_possession_yr": "财产年份",
    "c_possession_nh_code": "财产纪年年号ID",
    "c_possession_nh_yr": "财产纪年",
    "c_possession_yr_range": "财产年份区间",
    "c_quantity": "数量",
    "c_measure_code": "计量单位代码",
    "c_measure_desc": "计量单位",
    "c_measure_desc_chn": "计量单位",

    # ---- 元数据 ----
    "c_created_by": "录入者",
    "c_created_date": "录入日期",
    "c_modified_by": "最后修改者",
    "c_modified_date": "最后修改日期",

    # ---- 本项目自建：生平事件轴（View_PersonLifeTimeline / LIFE_EVENT_RESOLVED）----
    "stage_no": "阶段编号",
    "stage": "阶段",
    "event_label": "事件描述",
    "counterpart_type": "关联对象类型",
    "counterpart_id": "关联对象ID",
    "counterpart_name": "关联对象（拼音）",
    "counterpart_name_chn": "关联对象",
    "counterpart_is_person": "关联对象是否人物",
    "year_from": "起始年",
    "year_to": "终止年",
    "time_precision": "时间精度",
    "sort_year_lo": "排序年（下界）",
    "sort_year_hi": "排序年（上界）",
    "sort_year": "排序年",
    "sort_seq": "排序序号",
    "order_rank": "序轴序号",
    "prior_lo": "先验区间下界",
    "prior_hi": "先验区间上界",
    "prior_width": "先验区间宽",
    "lo": "区间下界",
    "hi": "区间上界",
    "width": "区间宽（年）",
    "narrowed": "是否被收窄",
    "precision": "精度等级",
    "conflict": "是否存在冲突",
    "locked": "年份是否锁定",
    "frame_src": "人生框架来源",

    # ---- 本项目自建：属性图边表（View_RelationEdges）----
    "src_type": "起点类型",
    "src_id": "起点ID",
    "src_name_chn": "起点名称",
    "dst_type": "终点类型",
    "dst_id": "终点ID",
    "dst_name_chn": "终点名称",
    "relation": "关系名",
    "edge_type": "边类型",

    # ---- 本项目自建：单本文献交游（View_TextAssociationData）----
    "source_dy": "文献所属朝代代码",
    "source_title": "文献名（拼音）",
    "source_title_chn": "文献名",
    "relation_category": "关系类别",
    "relation_desc_chn": "关系描述",
    "person_name": "人物姓名（拼音）",
    "person_name_chn": "人物姓名",
    "person_surname_chn": "人物姓",
    "person_female": "人物是否女性",
    "person_index_year": "人物指数年",
    "person_birthyear": "人物生年",
    "person_deathyear": "人物卒年",
    "person_dynasty_chn": "人物朝代",
    "person_choronym_chn": "人物郡望",
    "person_addr_chn": "人物地址",
    "c_person_name": "人物姓名（拼音）",
    "c_person_chn": "人物姓名",
}

# ---------------------------------------------------------------------------
# 二、按视图覆盖（只写含义确实不同的列）
# ---------------------------------------------------------------------------
VIEW_OVERRIDES = {
    # 著作表：c_title/c_textid 指「著作」，不是「出处文献」
    "View_BiogTextData": {
        "c_textid": "著作ID",
        "c_title": "著作名（拼音）",
        "c_title_chn": "著作名",
        "c_role_id": "著作角色代码",
        "c_role_desc": "著作角色",
        "c_role_desc_chn": "著作角色",
        "c_year": "成书 / 记载年",
        "c_source": "出处文献ID",
        "c_source_title": "出处文献名（拼音）",
        "c_source_chn": "出处文献名",
        "c_pages": "页码",
    },
    # 出处表：一行是「某人被某书收录」，c_title 是那本书
    "View_BiogSourceData": {
        "c_textid": "文献ID",
        "c_title": "文献名（拼音）",
        "c_title_chn": "文献名",
        "c_main_source": "是否主要出处",
        "c_pages": "页码",
    },
    "View_AltnameData": {
        "c_title": "别名出处文献名（拼音）",
        "c_title_chn": "别名出处文献名",
        "c_source": "别名出处文献ID",
        "c_sequence": "别名字号序号",
    },
    # 交游表：c_node_* 才是「这个人交往的对象」
    "View_AssociationData": {
        "c_node_id": "交游对象ID",
        "c_node_name": "交游对象（拼音）",
        "c_node_chn": "交游对象",
        "c_kin_chn": "同时在场亲属",
        "c_link_code": "关联代码",
        "c_link_desc": "关联类型",
        "c_link_chn": "关联类型",
        "c_assoc_kin_chn": "交游对象的亲属",
        "c_inst_name_hz": "关联机构名",
        "c_inst_name_py": "关联机构名（拼音）",
        "c_text_title": "记载文献",
        "c_source_title": "出处文献名（拼音）",
        "c_source_chn": "出处文献名",
        "c_range_chn": "年份区间（中文）",
    },
    "View_TextAssociationData": {
        "c_source": "文献ID",
        "source_title": "文献名（拼音）",
        "source_title_chn": "文献名",
        "c_year": "记载年份",
        "relation_category": "关系类别（亲属 / 社会 / 同书）",
        "relation_desc_chn": "关系说明",
        "c_personid": "人物ID",
        "counterpart_id": "对方人物ID",
        "counterpart_name": "对方姓名（拼音）",
        "counterpart_name_chn": "对方姓名",
        "counterpart_is_person": "对方是否人物",
    },
    "View_KinshipGenealogyData": {
        "c_personid": "本人ID",
        "kin_personid": "亲属ID",
        "person_name_chn": "本人姓名",
        "kin_name_chn": "亲属姓名",
        "c_kin_code": "亲属关系代码",
        "c_upstep": "本人相对亲属的上溯世代",
        "c_dwnstep": "本人相对亲属的下推世代",
        "c_source": "出处文献ID",
        "source_title_chn": "出处文献名",
        "source_title": "出处文献名（拼音）",
    },
    "View_KinAddrData": {
        "c_kin_id": "亲属ID",
        "c_kin_name": "亲属姓名（拼音）",
        "c_kin_chn": "亲属姓名",
        "c_addr_name": "亲属地址（拼音）",
        "c_addr_chn": "亲属地址",
        "c_title": "出处文献名（拼音）",
        "c_title_chn": "出处文献名",
        "c_sequence": "序号",
    },
    "View_PostingAddrData": {
        "c_posting_id": "任命ID",
        "c_office_id": "官职ID",
        "c_addr_id": "任职地点ID",
        "c_office_addr_name": "任职地点（拼音）",
        "c_office_addr_chn": "任职地点",
    },
    "View_PostingOfficeData": {
        "c_firstyear": "任职起始年",
        "c_lastyear": "任职终止年",
        "c_fy_range_desc": "任职起始年区间说明",
        "c_fy_range_chn": "任职起始年区间（中文）",
        "c_ly_range_desc": "任职终止年区间说明",
        "c_ly_range_chn": "任职终止年区间（中文）",
        "c_fy_month": "任职起始月",
        "c_fy_day": "任职起始日",
        "c_ly_month": "任职终止月",
        "c_ly_day": "任职终止日",
        "c_appt_desc": "任命类型",
        "c_appt_desc_chn": "任命类型",
        "c_source": "出处文献ID",
        "c_title": "出处文献名（拼音）",
        "c_title_chn": "出处文献名",
        "c_sequence": "同一年内的排序号",
    },
    "View_StatusData": {
        "c_firstyear": "身份起始年",
        "c_lastyear": "身份终止年",
        "c_fy_range_desc": "身份起始年区间说明",
        "c_fy_range_chn": "身份起始年区间（中文）",
        "c_ly_range_desc": "身份终止年区间说明",
        "c_ly_range_chn": "身份终止年区间（中文）",
        "c_fy_month": "身份起始月",
        "c_fy_day": "身份起始日",
        "c_ly_month": "身份终止月",
        "c_ly_day": "身份终止日",
        "c_title": "出处文献名（拼音）",
        "c_title_chn": "出处文献名",
        "c_sequence": "序号",
        "c_supplement": "补充信息",
    },
    "View_BiogAddrData": {
        "c_addr_id": "地点ID",
        "c_addr_name": "地名（拼音）",
        "c_addr_chn": "地名",
        "c_addr_desc": "地址类型代码",
        "c_addr_desc_chn": "地址类型",
        "c_firstyear": "该地址关系起始年",
        "c_lastyear": "该地址关系终止年",
        "c_fy_range_desc": "起始年区间说明",
        "c_fy_range_chn": "起始年区间（中文）",
        "c_ly_range_desc": "终止年区间说明",
        "c_ly_range_chn": "终止年区间（中文）",
        "c_fy_month": "起始月",
        "c_fy_day": "起始日",
        "c_ly_month": "终止月",
        "c_ly_day": "终止日",
        "c_source": "出处文献ID",
        "c_source_chn": "出处文献名",
        "c_source_title": "出处文献名（拼音）",
        "c_sequence": "序号",
    },
    "View_EntryData": {
        "c_year": "入仕年",
        "c_entry_nh_id": "入仕年号ID",
        "c_nianhao_chn": "入仕年号",
        "c_nianhao_pin": "入仕年号（拼音）",
        "c_entry_nh_year": "入仕纪年",
        "c_entry_range": "入仕年份区间",
        "c_range": "入仕年份区间",
        "c_range_chn": "入仕年份区间（中文）",
        "c_assoc_id": "相关人物ID",
        "c_assoc_name": "相关人物（拼音）",
        "c_assoc_name_chn": "相关人物（考官 / 推荐人等）",
        "c_assoc_code": "与相关人物的关系代码",
        "c_assoc_desc": "与相关人物的关系",
        "c_assoc_desc_chn": "与相关人物的关系",
        "c_kin_id": "相关亲属ID",
        "c_kin_name": "相关亲属（拼音）",
        "c_kin_name_chn": "相关亲属",
        "c_kin_code": "亲属关系代码",
        "c_kinrel": "亲属关系",
        "c_kinrel_chn": "亲属关系",
        "c_source": "出处文献ID",
        "c_title": "出处文献名（拼音）",
        "c_title_chn": "出处文献名",
        "c_sequence": "序号",
        "c_posting_notes": "任命备注",
    },
    "View_EventData": {
        "c_year": "事件年份",
        "c_nh_code": "事件年号ID",
        "c_nianhao_chn": "事件年号",
        "c_nianhao_pin": "事件年号（拼音）",
        "c_nh_year": "事件纪年",
        "c_yr_range": "事件年份区间",
        "c_range": "事件年份区间",
        "c_range_chn": "事件年份区间（中文）",
        "c_intercalary": "闰月",
        "c_month": "事件月",
        "c_day": "事件日",
        "c_day_ganzhi": "事件日干支",
        "c_role": "事件角色",
        "c_source": "出处文献ID",
        "c_source_title": "出处文献名（拼音）",
        "c_source_chn": "出处文献名",
    },
    "View_EventAddrData": {
        "c_year": "事件年份",
        "c_nh_code": "事件年号ID",
        "c_nianhao_chn": "事件年号",
        "c_nianhao_pin": "事件年号（拼音）",
        "c_nh_year": "事件纪年",
        "c_yr_range": "事件年份区间",
        "c_range": "事件年份区间",
        "c_range_chn": "事件年份区间（中文）",
        "c_intercalary": "闰月",
        "c_month": "事件月",
        "c_day": "事件日",
        "c_day_ganzhi": "事件日干支",
        "c_addr_id": "事件地点ID",
        "c_event_addr_name": "事件地点（拼音）",
        "c_event_addr_chn": "事件地点",
        "c_event_xcoord": "事件地点经度",
        "c_event_ycoord": "事件地点纬度",
        "c_person_name": "人物姓名（拼音）",
        "c_person_chn": "人物姓名",
    },
    "View_PossessionsData": {
        "c_possession_yr": "财产处置年份",
        "c_possession_nh_code": "处置纪年年号ID",
        "c_nianhao_chn": "处置纪年年号",
        "c_nianhao_pin": "处置纪年年号（拼音）",
        "c_possession_nh_yr": "处置纪年",
        "c_possession_yr_range": "处置年份区间",
        "c_range": "处置年份区间",
        "c_range_chn": "处置年份区间（中文）",
        "c_addr_id": "财产所在地ID",
        "c_title": "出处文献名（拼音）",
        "c_title_chn": "出处文献名",
        "c_sequence": "序号",
    },
    "View_PossessionsAddrData": {
        "c_possession_yr": "财产处置年份",
        "c_possession_yr_range": "处置年份区间",
        "c_range": "处置年份区间",
        "c_range_chn": "处置年份区间（中文）",
        "c_addr_id": "财产所在地ID",
        "c_possession_addr_name": "财产所在地（拼音）",
        "c_possession_addr_chn": "财产所在地",
        "c_sequence": "序号",
    },
    "View_BiogInstData": {
        "c_bi_role_code": "机构任职角色代码",
        "c_bi_begin_year": "任职起始年",
        "c_bi_end_year": "任职终止年",
        "c_source": "出处文献ID",
        "c_source_chn": "出处文献名",
        "c_source_py": "出处文献名（拼音）",
        "c_inst_addr_id": "机构所在地ID",
        "c_inst_addr_type_code": "机构所在地类型代码",
    },
    "View_BiogInstAddrData": {
        "c_bi_role_code": "机构任职角色代码",
        "c_bi_begin_year": "任职起始年",
        "c_bi_end_year": "任职终止年",
        "c_source": "出处文献ID",
        "c_source_chn": "出处文献名",
        "c_source_py": "出处文献名（拼音）",
        "c_inst_addr_id": "机构所在地ID",
        "c_inst_addr_type_code": "机构所在地类型代码",
        "c_inst_addr_type_desc": "机构所在地类型",
        "c_inst_addr_type_chn": "机构所在地类型",
        "c_inst_addr_pinyin": "机构所在地（拼音）",
        "c_inst_addr_chn": "机构所在地",
    },
    "View_PeopleData": {
        "c_index_addr_id": "索引地址ID",
        "c_index_addr_name": "索引地址（拼音）",
        "c_index_addr_chn": "索引地址",
        "c_addr_desc": "索引地址类型代码",
        "c_addr_desc_chn": "索引地址类型",
        "c_source_title": "指数年依据文献（拼音）",
        "c_source_chn": "指数年依据文献",
    },
    "View_PeopleAddrData": {
        "c_index_addr_id": "索引地址ID",
        "c_index_addr_name": "索引地址（拼音）",
        "c_index_addr_chn": "索引地址",
        "c_index_addr_type_code": "索引地址类型代码",
        "c_index_addr_type_desc": "索引地址类型",
        "c_index_addr_type_chn": "索引地址类型",
    },
    "View_CountyPeopleData": {
        "person_name_chn": "人物姓名",
        "person_name": "人物姓名（拼音）",
        "dynasty_chn": "人物朝代",
        "county_addr_id": "县ID",
        "county_name_chn": "县名",
        "county_name": "县名（拼音）",
        "c_source": "出处文献ID",
        "source_title_chn": "出处文献名",
        "c_natal": "该地址是否籍贯",
        "addr_relation_chn": "该人物与本县的关系",
    },
    "View_PersonLifeTimeline": {
        "c_personid": "人物ID",
        "stage_no": "阶段编号",
        "stage": "阶段",
        "event_label": "事件描述",
        "counterpart_type": "关联对象类型",
        "counterpart_id": "关联对象ID",
        "counterpart_name_chn": "关联对象",
        "year_from": "起始年",
        "year_to": "终止年",
        "time_precision": "时间精度",
        "sort_year_lo": "排序年（下界）",
        "sort_year_hi": "排序年（上界）",
        "sort_year": "排序年",
        "sort_seq": "排序序号",
        "c_source": "出处文献ID",
    },
    "LIFE_EVENT_RESOLVED": {
        "c_personid": "人物ID",
        "order_rank": "序轴序号（同阶段内）",
        "stage_no": "阶段编号",
        "stage": "阶段",
        "event_label": "事件描述",
        "counterpart_name_chn": "关联对象",
        "time_precision": "时间精度",
        "prior_lo": "先验区间下界",
        "prior_hi": "先验区间上界",
        "prior_width": "先验区间宽（年）",
        "lo": "收窄后区间下界",
        "hi": "收窄后区间上界",
        "width": "收窄后区间宽（年）",
        "narrowed": "是否被收窄",
        "precision": "精度等级",
        "conflict": "是否存在冲突",
        "locked": "年份是否锁定",
        "frame_src": "人生框架来源",
        "c_source": "出处文献ID",
    },
    "View_RelationEdges": {
        "src_type": "起点类型（P人/A地/O官/I机构/T文献…）",
        "src_id": "起点ID",
        "src_name_chn": "起点名称",
        "dst_type": "终点类型",
        "dst_id": "终点ID",
        "dst_name_chn": "终点名称",
        "relation": "关系名",
        "edge_type": "边类型（亲属 / 交游 / 任官…）",
        "year_from": "起始年",
        "year_to": "终止年",
        "time_precision": "时间精度",
        "c_source": "出处文献ID",
    },
}

# join_keys 里出现的列，中文名要更明确（它们是最重要的下钻键）
KEY_LABELS = {
    "c_personid": "人物ID",
    "kin_personid": "亲属ID",
    "c_kin_id": "亲属ID",
    "c_assoc_id": "交游对象ID",
    "c_addr_id": "地点ID",
    "county_addr_id": "县ID",
    "c_office_id": "官职ID",
    "c_source": "出处文献ID",
    "c_textid": "文献ID",
    "c_inst_code": "机构ID",
    "c_status_code": "身份代码",
    "c_event_code": "事件代码",
    "c_entry_code": "入仕途径代码",
    "c_kin_code": "亲属关系代码",
    "c_assoc_code": "交游关系代码",
    "c_posting_id": "任命ID",
}


# ---------------------------------------------------------------------------
# 三、视图中文名（24 个视图的英文名对新人同样不友好）
# ---------------------------------------------------------------------------
VIEW_LABELS = {
    "View_PeopleData": ("人物主表", "全部人物的基本信息、指数年、生卒、索引地址"),
    "View_PeopleAddrData": ("人物索引地址", "人物的索引地址与经纬度"),
    "View_BiogSourceData": ("人物史料出处", "每位人物被哪些文献著录、页码与链接"),
    "View_AltnameData": ("别名字号", "字、号、谥号等别名及出处"),
    "View_PersonLifeTimeline": ("生平事件时间轴", "14 个阶段的事件流（本项目新增）"),
    "LIFE_EVENT_RESOLVED": ("区间轴求解结果", "STP 传播后的区间 lo/hi 与精度（本项目新增）"),
    "View_RelationEdges": ("关系边表（图）", "属性图边表，供链式遍历（本项目新增）"),
    "View_KinshipGenealogyData": ("亲属与族谱", "亲属关系、世代差、谱系类型"),
    "View_KinAddrData": ("亲属地址", "亲属的地址记录与出处"),
    "View_AssociationData": ("社会关系与交游", "非亲属社会关系、场合、主题、体裁"),
    "View_TextAssociationData": ("单本文献交游", "按单本文献还原的交往世界（本项目新增）"),
    "View_EntryData": ("入仕记录", "科举 / 门荫等入仕途径、名次、相关人物"),
    "View_PostingOfficeData": ("历任官职", "任职起止、任命类型、就任方式、机构"),
    "View_PostingAddrData": ("任官治所", "官职对应的治所地点"),
    "View_BiogAddrData": ("人物地址", "人物的各类地址关系与所属政区"),
    "View_CountyPeopleData": ("县级政区人物", "按县统计的人物（本项目新增）"),
    "View_EventAddrData": ("事件地点", "事件发生地点"),
    "View_StatusData": ("社会身份", "身份起止年、补充信息"),
    "View_BiogInstData": ("所属机构", "人物所属机构与机构任职角色"),
    "View_BiogInstAddrData": ("机构与所在地", "机构、角色与所在地详情"),
    "View_BiogTextData": ("著述", "人物著作、著作角色、成书年"),
    "View_EventData": ("参与事件", "人物参与的历史事件与角色"),
    "View_PossessionsData": ("财产处置", "财产数量、处置方式（数据量极小）"),
    "View_PossessionsAddrData": ("财产与所在地", "财产处置记录与所在地"),
}


def view_label(name: str) -> str:
    v = VIEW_LABELS.get(name)
    return v[0] if v else name


def view_desc(name: str, fallback: str = "") -> str:
    v = VIEW_LABELS.get(name)
    return v[1] if v else fallback


def resolve(view: str, col: str) -> str:
    """取某视图下某列的中文名；没有就返回空串（前端回落到原始列名）。"""
    ov = VIEW_OVERRIDES.get(view, {})
    return ov.get(col) or COLUMN_LABELS.get(col, "")


def labels_for(view: str, cols) -> dict:
    """只保留有中文名的列，减少 JSON 体积。"""
    out = {}
    for c in cols:
        t = resolve(view, c)
        if t:
            out[c] = t
    return out


def all_known() -> set:
    s = set(COLUMN_LABELS)
    for m in VIEW_OVERRIDES.values():
        s |= set(m)
    return s
